### ISSUE TITLE
Can't build on fedora 36 due to openssl 3

### ISSUE THREAD

**Issue by stemid** [negativo17/Signal-Desktop#4]
It appears that openssl 3 on fedora36 is preventing me from building this suddenly, btw I've used and loved these files for years now. I really appreciate the work you put in for us who don't understand the react/webpack build systems.

With standard fedora 36 packages I can only get nodejs 16 or 18. And I get the same error, so I tried installing nvm and nodejs 17 and removed the npm dependency from the spec file but still same error. So I think I can say I've tried all 3 latest versions.

But here is the error I get;

```
[build:webpack   ] Error: error:0308010C:digital envelope routines::unsupported
[build:webpack   ]     at new Hash (node:internal/crypto/hash:67:19)
[build:webpack   ]     at Object.createHash (node:crypto:130:10)
[build:webpack   ]     at BulkUpdateDecorator.hashFactory (/home/stemid/src/rpmbuild/BUILD/Signal-Desktop-5.62.0/node_modules/webpack/lib/util/createHash.js:144:18)
[build:webpack   ]     at BulkUpdateDecorator.update (/home/stemid/src/rpmbuild/BUILD/Signal-Desktop-5.62.0/node_modules/webpack/lib/util/createHash.js:46:50)
[build:webpack   ]     at RawSource.updateHash (/home/stemid/src/rpmbuild/BUILD/Signal-Desktop-5.62.0/node_modules/webpack/node_modules/webpack-sources/lib/RawSource.js:64:8)
[build:webpack   ]     at NormalModule._initBuildHash (/home/stemid/src/rpmbuild/BUILD/Signal-Desktop-5.62.0/node_modules/webpack/lib/NormalModule.js:838:17)
[build:webpack   ]     at handleParseResult (/home/stemid/src/rpmbuild/BUILD/Signal-Desktop-5.62.0/node_modules/webpack/lib/NormalModule.js:903:10)
[build:webpack   ]     at /home/stemid/src/rpmbuild/BUILD/Signal-Desktop-5.62.0/node_modules/webpack/lib/NormalModule.js:994:4
[build:webpack   ]     at processResult (/home/stemid/src/rpmbuild/BUILD/Signal-Desktop-5.62.0/node_modules/webpack/lib/NormalModule.js:717:11)
[build:webpack   ]     at /home/stemid/src/rpmbuild/BUILD/Signal-Desktop-5.62.0/node_modules/webpack/lib/NormalModule.js:777:5
[build:webpack   ] error Command failed with exit code 1.
[build:webpack   ] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[build:webpack   ] ERROR: "build:webpack:sticker-creator" exited with 1.
[build:webpack   ] error Command failed with exit code 1.
[build:webpack   ] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build:webpack" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error: Bad exit status from /home/stemid/src/rpmbuild/tmp/rpm-tmp.JDZxzz (%build)
```

And everything I find online about this error indicates that it's lack of legacy support in openssl3. I tried setting NODE_OPTIONS="--openssl-legacy-provider" but I just get an error from node saying I'm not allowed to set that.

**Comment by scaronni** [comment]
Hi, may I ask you why are you rebuilding the package and not just consuming it as is? Maybe I can just add what you miss and you don't need to rebuild.

Unfortunately there is no workaround, as `nodejs` has been patched on Fedora 36+ to support OpenSSL 3 while the Signal project still is not up to date.

At the moment you can use Fedora 35 `mock chroots` to generate the RPM or use the upstream `nodejs` repository in your `mock` configuration.

**Comment by scaronni** [comment]
Btw, it now builds with the bundled Node.js in Fedora. Just figured out I could reduce the scope of the build (not a `yarn/nodejs` expert): https://github.com/negativo17/Signal-Desktop/commit/baba0a47a69ca97abd9ef03f2ff6f3f1ee293be1
